### ISSUE TITLE
比較條文 checkbox 改為 section link；網頁往下捲時能保持 position: sticky;

### ISSUE THREAD

**Issue by typingmonk** [openfunltd/law-diff-frontend#1]
### Description
套上實際資料後發現提案經常一口氣改了很多個條文，使得勾選比較條文的動作變得很繁瑣。經討論後決定將 checkbox 改為 section link。

### Request
- 根據勾選的版本陳列所有的條文，不必再勾選想要的比較條文。
- checkbox 改成 `<a href="#{條文id}">` ，點擊時網頁下拉到該條文 `<div class="title" id="{條文id}">`
- 比較條文 `<div class="available-sections">` 在網頁下拉時能維持在畫面上 `position: sticky;`，使用者不用往上拉回去點選，隨時在網頁左側點擊想看的比較條文。

**Comment by boggyjan** [comment]
done!

**Comment by typingmonk** [comment]
### Updated Request
實裝後發現實際數據的比較條文項目很多，很容易就超過整個瀏覽器的最高高度，使得 `position: sticky;` 會讓後面的 <a> 點不到。
- 麻煩請幫我把比較條文的 `position: sticky;` 拿掉。

**Comment by boggyjan** [comment]
ok fixed

**Comment by typingmonk** [comment]
### Update Request
經討論後改成 sticky and scroll
Done in: https://github.com/openfunltd/law-diff-frontend/commit/26fbacdf5f2a3d448f834e64970f40a388333297
