### ISSUE TITLE
讓 bill result 內的文字可以反白選擇

### ISSUE THREAD

**Issue by typingmonk** [openfunltd/law-diff-frontend#8]
上次 demo 有使用者反應無法反白選擇查詢結果呈現的 bill result，原因是目前每一個 bill result 最外層是用 `<a>` 包起來，導致游標滑過去時整個 bill result 區塊滑鼠都是 index finger 的狀態。
希望能改成其他的包法包每一個 bill result，讓使用者能反白選擇/複製看到的結果。

**Comment by boggyjan** [comment]
改好囉
1. 外框改為 div tag移除href
2. 標題改為a tag

**Comment by typingmonk** [comment]
原來這麼簡單～
感謝 boggy
Issue close
