### ISSUE TITLE
讓「立法理由」能反白選擇

### ISSUE THREAD

**Issue by typingmonk** [openfunltd/law-diff-frontend#9]
目前對照表中立法理由 `class="bill-reason"` 是用滑鼠點擊開展收合文字，但使用者反應有想複製文字的需求，用滑鼠反白複製內文時就收合了。
希望能提供一個可供點擊的箭頭/圖案來執行展開收合的動作，或是其他方法能不會妨礙複製文字的前端呈現方式都可以。

**Comment by boggyjan** [comment]
修正囉
請協助覆蓋 js/common.js

**Comment by typingmonk** [comment]
Thank you for the fix. Issue close.
